<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <BlazorCacheBootResources>false</BlazorCacheBootResources>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove=".github\**" />
    <Content Remove=".github\**" />
    <EmbeddedResource Remove=".github\**" />
    <None Remove=".github\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.6" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\T4Dungeon\T4Dungeon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\.nojekyll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
