
// <auto-generated>
// Generated by T4
// </auto-generated>

namespace T4Dungeon.Generated
{
    public enum ItemId
    {
        RustyDagger = 1001,
        IronSword = 1002,
        Warhammer = 1003,
        WizardStaff = 1004,
        Longbow = 1005,
        Excalibur = 1006,
        ClothTunic = 1101,
        LeatherArmor = 1102,
        Chainmail = 1103,
        PlateArmor = 1104,
        WoodenShield = 1105,
        DragonScale = 1106,
        OldPenny = 1201,
        ApprenticeRing = 1202,
        IronBand = 1203,
        AmuletofLife = 1204,
        ChaosOrb = 1205,
        StormPendant = 1206,
        ShieldRing = 1207,
        BerserkerCharm = 1208,
        HealthPotion = 2001,
        ManaPotion = 2002,
        FireScroll = 2003,
        IronSkinElixir = 2004,
        Torch = 2005,
    }
}