<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Art\Ascii Art\" />
    <Folder Include="CodeGen\Includes\" />
    <Folder Include="CodeGen\Settings\" />
    <Folder Include="Data\Events\" />
    <Folder Include="Data\Floors\" />
    <Folder Include="Data\Schemas\" />
    <Folder Include="Generated\Enemies\" />
    <Folder Include="Generated\Events\" />
    <Folder Include="Generated\Items\" />
    <Folder Include="Generated\Shares\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="CodeGen\Templates\EnemyDatabase.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EnemyDatabase.tt</DependentUpon>
    </None>
    <None Include="CodeGen\Templates\EnemyIds.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EnemyIds.tt</DependentUpon>
    </None>
    <None Include="CodeGen\Templates\Enums.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Enums.tt</DependentUpon>
    </None>
    <None Include="CodeGen\Templates\ItemDatabase.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ItemDatabase.tt</DependentUpon>
    </None>
    <None Include="CodeGen\Templates\LootDatabase.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LootDatabase.tt</DependentUpon>
    </None>
    <None Include="CodeGen\Templates\SkillIds.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SkillIds.tt</DependentUpon>
    </None>
    <None Include="CodeGen\Templates\SkillsDatabase.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SkillsDatabase.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="CodeGen\Templates\ItemIds.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ItemIds.cs</LastGenOutput>
    </None>
    <None Update="CodeGen\Templates\Enums.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Enums.cs</LastGenOutput>
    </None>
    <None Update="CodeGen\Templates\ItemDatabase.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ItemDatabase.cs</LastGenOutput>
    </None>
    <None Update="CodeGen\Templates\EnemyIds.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>EnemyIds.cs</LastGenOutput>
    </None>
    <None Update="CodeGen\Templates\EnemyDatabase.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>EnemyDatabase.cs</LastGenOutput>
    </None>
    <None Update="CodeGen\Templates\SkillIds.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>SkillIds.cs</LastGenOutput>
    </None>
    <None Update="CodeGen\Templates\SkillsDatabase.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>SkillsDatabase.cs</LastGenOutput>
    </None>
    <None Update="CodeGen\Templates\LootDatabase.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>LootDatabase.cs</LastGenOutput>
    </None>
    <None Update="Data\Maps\tutorial_map.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CodeGen\Templates\EnemyDatabase.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EnemyDatabase.tt</DependentUpon>
    </Compile>
    <Compile Update="CodeGen\Templates\EnemyIds.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EnemyIds.tt</DependentUpon>
    </Compile>
    <Compile Update="CodeGen\Templates\Enums.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Enums.tt</DependentUpon>
    </Compile>
    <Compile Update="CodeGen\Templates\ItemDatabase.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ItemDatabase.tt</DependentUpon>
    </Compile>
    <Compile Update="CodeGen\Templates\ItemIds.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ItemIds.tt</DependentUpon>
    </Compile>
    <Compile Update="CodeGen\Templates\LootDatabase.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LootDatabase.tt</DependentUpon>
    </Compile>
    <Compile Update="CodeGen\Templates\SkillIds.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SkillIds.tt</DependentUpon>
    </Compile>
    <Compile Update="CodeGen\Templates\SkillIs.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SkillIs.tt</DependentUpon>
    </Compile>
    <Compile Update="CodeGen\Templates\SkillsDatabase.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SkillsDatabase.tt</DependentUpon>
    </Compile>
    <Compile Update="CodeGen\Templates\TextTemplate1.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TextTemplate1.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

</Project>
